name: Preprocessing_Heart_Data_Pipeline

on:
  push:
    paths:
      - 'heart.csv'                       # Trigger if raw data at root changes
      - 'preprocessing/automate_carolus.py' # Trigger if script changes
      - '.github/workflows/**'             # Trigger if workflow itself changes
  workflow_dispatch: # Allows manual triggering

jobs:
  preprocess-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Or your preferred Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas scikit-learn numpy

      - name: Run preprocessing script
        # Execute the script located in the preprocessing folder
        run: python preprocessing/automate_carolus.py

      - name: Upload processed dataset as artifact
        uses: actions/upload-artifact@v4
        with:
          name: processed-heart-data-artifact # Name for the downloadable artifact
          # Path to the processed file, now directly inside the preprocessing/ folder
          path: preprocessing/processed_heart_data.csv
          retention-days: 7 # Optional: How long to keep the artifact

      # Optional: Commit the processed data back to the repository
      - name: Commit processed data (Optional)
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          # Add the specific processed file using its correct path
          git add preprocessing/processed_heart_data.csv
          
          # Check if there are changes to commit to avoid empty commits
          if git diff --staged --quiet; then
            echo "No changes to commit in processed_heart_data.csv."
          else
            git commit -m "Automated preprocessing: Update processed_heart_data.csv"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Default token, usually sufficient for same-repo pushes